name: Test

on:
  push:
    branches:
      - master

env:
  USE_SYSTEM_PYTHON: 3

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: setup python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: pip caching
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Test
        run: |
          ./black.sh
          ./flake8.sh
          ./isort.sh
          ./mypy.sh
          ./pytest.sh
